// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-1NmVxISRRAPwEM8HeWC0T85QhmZRe30',
    appId: '1:263774418399:web:b5decfe9ad7f064bcb806a',
    messagingSenderId: '263774418399',
    projectId: 'chat-app-3981f',
    authDomain: 'chat-app-3981f.firebaseapp.com',
    storageBucket: 'chat-app-3981f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARp3bON_rPx0PsnD0gRGY_RTzNmqkGFVc',
    appId: '1:263774418399:android:86c6910153aaa67dcb806a',
    messagingSenderId: '263774418399',
    projectId: 'chat-app-3981f',
    storageBucket: 'chat-app-3981f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfYsOUf-8v2ek5g9zFnK2MqhwCItb3v0o',
    appId: '1:263774418399:ios:15cc9b019ec8d6fdcb806a',
    messagingSenderId: '263774418399',
    projectId: 'chat-app-3981f',
    storageBucket: 'chat-app-3981f.appspot.com',
    iosClientId: '263774418399-p7js8aechm8l2bojib9u3um462lneblu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfYsOUf-8v2ek5g9zFnK2MqhwCItb3v0o',
    appId: '1:263774418399:ios:614bf473230f271ccb806a',
    messagingSenderId: '263774418399',
    projectId: 'chat-app-3981f',
    storageBucket: 'chat-app-3981f.appspot.com',
    iosClientId: '263774418399-nreq5tml2shdmc6udi3bb8j0admegfaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
